-- =============================================================================
-- Sa7tein — ALIGN TO DOC (DESTRUKTIF)  →  pilihan "A"
-- =============================================================================
-- Menyelaraskan schema `public` ke docs/product/schema-draft-v1.md (17 entitas)
-- + `notifications` (dipakai UI). Uang DUA kolom: *_idr + *_jod.
--
-- DESTRUKTIF: menghapus SELURUH tabel public yang ada lalu membuat ulang.
-- Data lama ada di backup: lihat supabase/README.md. Jalankan dalam transaksi.
-- =============================================================================

begin;

-- 1) Buang semua tabel public yang ada (fungsi app_* dipertahankan)
do $$
declare r record;
begin
  for r in select tablename from pg_tables where schemaname = 'public' loop
    execute format('drop table if exists public.%I cascade', r.tablename);
  end loop;
end $$;

-- 2) Tabel target
create table public.users (
  id            bigint generated by default as identity primary key,
  auth_user_id  uuid unique,
  type          text not null check (type in ('customer', 'courier', 'merchant', 'cs', 'superadmin')),
  email         text,
  phone         text,
  verified      boolean not null default false,
  status        text not null default 'active' check (status in ('active', 'suspended')),
  auth_provider text,
  created_at    timestamptz not null default now()
);

create table public.marketing (
  id          bigint generated by default as identity primary key,
  type        text check (type in ('promo_delivery', 'discount_pct', 'discount_fixed')),
  value       numeric,
  code        text,
  active_from timestamptz,
  active_to   timestamptz,
  max_uses    integer,
  used_count  integer not null default 0,
  created_at  timestamptz not null default now()
);

create table public.merchants (
  id              bigint generated by default as identity primary key,
  user_id         bigint references public.users (id) on delete cascade,
  name            text,
  description     text,
  photo           text,
  available       boolean not null default true,
  delivery_config jsonb not null default '{}'::jsonb,
  tenant_status   text not null default 'pending' check (tenant_status in ('pending', 'approved', 'suspended', 'blacklisted')),
  deposit_idr     numeric not null default 0,
  deposit_jod     numeric not null default 0,
  deposit_status  text not null default 'unpaid' check (deposit_status in ('unpaid', 'held', 'released')),
  created_at      timestamptz not null default now()
);

create table public.customers (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references public.users (id) on delete cascade,
  name       text,
  risk_flag  boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.addresses (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references public.users (id) on delete cascade,
  label      text,
  address    text,
  latitude   double precision,
  longitude  double precision,
  is_default boolean not null default false,
  zone       text check (zone in ('A', 'B', 'C')),
  created_at timestamptz not null default now()
);

create table public.couriers (
  id           bigint generated by default as identity primary key,
  user_id      bigint references public.users (id) on delete cascade,
  merchant_id  bigint references public.merchants (id) on delete cascade,
  availability text not null default 'available' check (availability in ('available', 'unavailable', 'busy')),
  created_at   timestamptz not null default now()
);

create table public.menus (
  id          bigint generated by default as identity primary key,
  merchant_id bigint references public.merchants (id) on delete cascade,
  name        text,
  description text,
  price_idr   numeric not null default 0,
  price_jod   numeric not null default 0,
  available   boolean not null default true,
  image       text,
  created_at  timestamptz not null default now()
);

create table public.menu_variants (
  id         bigint generated by default as identity primary key,
  menu_id    bigint references public.menus (id) on delete cascade,
  name       text,
  required   boolean not null default false,
  max_select integer not null default 1,
  options    jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table public.batches (
  id                    bigint generated by default as identity primary key,
  merchant_id           bigint references public.merchants (id),
  courier_id            bigint references public.couriers (id),
  status                text not null default 'prepare' check (status in ('prepare', 'closed', 'waitingCourier', 'waitingDelivery', 'delivery')),
  eta_prepare           integer,
  eta_delivery          integer,
  sla_prepare_deadline  timestamptz,
  sla_delivery_deadline timestamptz,
  escalated_to_admin    boolean not null default false,
  created_at            timestamptz not null default now()
);

create table public.orders (
  id                  bigint generated by default as identity primary key,
  code                text unique,
  status              text not null default 'cart' check (status in ('cart', 'quotation', 'canceled', 'prepare', 'waitingCourier', 'waitingDelivery', 'delivery', 'done')),
  customer_id         bigint references public.customers (id),
  merchant_id         bigint references public.merchants (id),
  delivery_address_id bigint references public.addresses (id),
  batch_id            bigint references public.batches (id),
  sub_total_idr       numeric not null default 0,
  sub_total_jod       numeric not null default 0,
  delivery_fee_idr    numeric not null default 0,
  delivery_fee_jod    numeric not null default 0,
  platform_fee_idr    numeric not null default 0,
  platform_fee_jod    numeric not null default 0,
  total_idr           numeric not null default 0,
  total_jod           numeric not null default 0,
  payment_method      text check (payment_method in ('cod', 'transfer', 'xendit_va', 'xendit_qris')),
  payment_status      text not null default 'unpaid' check (payment_status in ('unpaid', 'pending', 'paid', 'failed', 'refunded')),
  paid_at             timestamptz,
  placed_at           timestamptz,
  cancel_reason       text,
  cancel_by           text check (cancel_by in ('customer', 'merchant', 'system')),
  tip_idr             numeric not null default 0,
  tip_jod             numeric not null default 0,
  zone                text check (zone in ('A', 'B', 'C')),
  promo_id            bigint references public.marketing (id),
  promo_amount_idr    numeric not null default 0,
  promo_amount_jod    numeric not null default 0,
  created_at          timestamptz not null default now()
);

create table public.order_items (
  id              bigint generated by default as identity primary key,
  order_id        bigint references public.orders (id) on delete cascade,
  menu_id         bigint references public.menus (id),
  qty             integer not null default 1,
  unit_price_idr  numeric not null default 0,
  unit_price_jod  numeric not null default 0,
  modifiers       jsonb not null default '[]'::jsonb,
  line_total_idr  numeric not null default 0,
  line_total_jod  numeric not null default 0,
  note            text
);

create table public.fav_merchants (
  id          bigint generated by default as identity primary key,
  user_id     bigint not null references public.users (id) on delete cascade,
  merchant_id bigint not null references public.merchants (id) on delete cascade,
  created_at  timestamptz not null default now(),
  unique (user_id, merchant_id)
);

create table public.wallets (
  id                   bigint generated by default as identity primary key,
  user_id              bigint not null references public.users (id) on delete cascade,
  balance_idr          numeric not null default 0,
  balance_jod          numeric not null default 0,
  reserved_balance_idr numeric not null default 0,
  reserved_balance_jod numeric not null default 0,
  updated_at           timestamptz not null default now(),
  created_at           timestamptz not null default now()
);

create table public.ledgers (
  id         bigint generated by default as identity primary key,
  user_id    bigint references public.users (id),
  order_id   bigint references public.orders (id),
  type       text check (type in ('cr', 'db')),
  reference  text check (reference in ('topUp', 'order', 'delivery', 'withdrawal', 'refund', 'hold', 'release')),
  amount_idr numeric,
  amount_jod numeric,
  created_at timestamptz not null default now()
);

create table public.chats (
  id           bigint generated by default as identity primary key,
  order_id     bigint references public.orders (id) on delete cascade,
  last_message text,
  last_at      timestamptz,
  created_at   timestamptz not null default now()
);

create table public.chat_messages (
  id        bigint generated by default as identity primary key,
  chat_id   bigint references public.chats (id) on delete cascade,
  sender_id bigint references public.users (id),
  body      text,
  at        timestamptz not null default now(),
  read_at   timestamptz
);

create table public.incident_resolutions (
  id                bigint generated by default as identity primary key,
  order_id          bigint references public.orders (id) on delete cascade,
  opened_by         bigint references public.users (id),
  type              text check (type in ('late', 'missing', 'wrong', 'not_delivered', 'payment_failed')),
  status            text not null default 'open' check (status in ('open', 'investigating', 'resolved', 'rejected')),
  resolution        text check (resolution in ('refund_customer', 'refund_order', 'resettle', 'no_action')),
  refund_amount_idr numeric,
  refund_amount_jod numeric,
  resolved_by       bigint references public.users (id),
  resolved_at       timestamptz,
  created_at        timestamptz not null default now()
);

create table public.rating_reviews (
  id          bigint generated by default as identity primary key,
  order_id    bigint references public.orders (id) on delete cascade,
  merchant_id bigint references public.merchants (id),
  customer_id bigint references public.customers (id),
  menu_id     bigint references public.menus (id),
  review      text,
  rating      integer check (rating between 1 and 5),
  created_at  timestamptz not null default now()
);

create table public.notifications (
  id         bigint generated by default as identity primary key,
  user_id    bigint references public.users (id) on delete cascade,
  kind       text,
  title      text,
  body       text,
  time       timestamptz not null default now(),
  unread     boolean not null default true,
  created_at timestamptz not null default now()
);

-- 3) Index bantu
create index on public.orders (customer_id);
create index on public.orders (merchant_id);
create index on public.orders (batch_id);
create index on public.order_items (order_id);
create index on public.menus (merchant_id);
create index on public.menu_variants (menu_id);
create index on public.wallets (user_id);
create index on public.ledgers (user_id);
create index on public.notifications (user_id);

-- 4) RLS: ops penuh di semua tabel, owner di tabel ber-user, baca publik menu/katalog
do $$
declare r record;
begin
  for r in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table public.%I enable row level security', r.tablename);
    execute format(
      'create policy %I on public.%I for all to public using (public.app_is_ops()) with check (public.app_is_ops())',
      r.tablename || '_ops', r.tablename
    );
  end loop;
end $$;

create policy users_self on public.users
  for all to public using (auth_user_id = auth.uid()) with check (auth_user_id = auth.uid());
create policy addresses_owner on public.addresses
  for all to public using (user_id = public.app_uid()) with check (user_id = public.app_uid());
create policy customers_owner on public.customers
  for all to public using (user_id = public.app_uid()) with check (user_id = public.app_uid());
create policy merchants_owner on public.merchants
  for all to public using (user_id = public.app_uid()) with check (user_id = public.app_uid());
create policy couriers_owner on public.couriers
  for all to public using (user_id = public.app_uid()) with check (user_id = public.app_uid());
create policy fav_merchants_owner on public.fav_merchants
  for all to public using (user_id = public.app_uid()) with check (user_id = public.app_uid());
create policy wallets_owner on public.wallets
  for all to public using (user_id = public.app_uid()) with check (user_id = public.app_uid());
create policy ledgers_owner on public.ledgers
  for all to public using (user_id = public.app_uid()) with check (user_id = public.app_uid());
create policy notifications_owner on public.notifications
  for all to public using (user_id = public.app_uid()) with check (user_id = public.app_uid());

create policy menus_public_read on public.menus for select to public using (true);
create policy menu_variants_public_read on public.menu_variants for select to public using (true);
create policy marketing_public_read on public.marketing for select to public using (true);
create policy rating_reviews_public_read on public.rating_reviews for select to public using (true);

-- customer boleh baca order miliknya
create policy orders_customer_read on public.orders
  for select to public
  using (customer_id in (select id from public.customers where user_id = public.app_uid()));

commit;
