-- Seed people: customer, kurir, admin (cs), super admin. Idempoten.
begin;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (13, 'customer', 'customer2@sa7tein.app', '+962790001010', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.customers (id, user_id, name, risk_flag) overriding system value values (2, 13, 'Ahmad Fauzi', false) on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (14, 'customer', 'customer3@sa7tein.app', '+962790001011', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.customers (id, user_id, name, risk_flag) overriding system value values (3, 14, 'Siti Aminah', false) on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (15, 'customer', 'customer4@sa7tein.app', '+962790001012', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.customers (id, user_id, name, risk_flag) overriding system value values (4, 15, 'Omar Haddad', false) on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (16, 'customer', 'customer5@sa7tein.app', '+962790001013', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.customers (id, user_id, name, risk_flag) overriding system value values (5, 16, 'Lina Khalil', false) on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (17, 'customer', 'customer6@sa7tein.app', '+962790001014', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.customers (id, user_id, name, risk_flag) overriding system value values (6, 17, 'Rizky Pratama', false) on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (18, 'customer', 'customer7@sa7tein.app', '+962790001015', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.customers (id, user_id, name, risk_flag) overriding system value values (7, 18, 'Nadia Salsabila', false) on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (19, 'courier', 'courier2@sa7tein.app', '+962790002010', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.couriers (id, user_id, merchant_id, name, availability) overriding system value values (2, 19, 2, 'Andi Saputra', 'available') on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (20, 'courier', 'courier3@sa7tein.app', '+962790002011', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.couriers (id, user_id, merchant_id, name, availability) overriding system value values (3, 20, 3, 'Yusuf Karim', 'busy') on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (21, 'courier', 'courier4@sa7tein.app', '+962790002012', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.couriers (id, user_id, merchant_id, name, availability) overriding system value values (4, 21, 4, 'Hasan Basri', 'available') on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (22, 'courier', 'courier5@sa7tein.app', '+962790002013', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.couriers (id, user_id, merchant_id, name, availability) overriding system value values (5, 22, 5, 'Slamet Riyadi', 'unavailable') on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (23, 'courier', 'courier6@sa7tein.app', '+962790002014', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.couriers (id, user_id, merchant_id, name, availability) overriding system value values (6, 23, 6, 'Rizal Maulana', 'available') on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (24, 'cs', 'cs2@sa7tein.app', '+962790003010', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.operators (id, user_id, role_id, active) overriding system value values (1, 24, 1, true) on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (25, 'cs', 'cs3@sa7tein.app', '+962790003011', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.operators (id, user_id, role_id, active) overriding system value values (2, 25, 1, true) on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (26, 'superadmin', 'owner@sa7tein.app', '+962790004013', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.operators (id, user_id, role_id, active) overriding system value values (3, 26, 3, true) on conflict (id) do nothing;
insert into public.users (id, role, email, phone, verified, status, auth_provider) overriding system value values (27, 'superadmin', 'ops@sa7tein.app', '+962790004014', true, 'active', 'phone') on conflict (id) do nothing;
insert into public.operators (id, user_id, role_id, active) overriding system value values (4, 27, 2, true) on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.users','id'), (select max(id) from public.users));
select setval(pg_get_serial_sequence('public.customers','id'), (select max(id) from public.customers));
select setval(pg_get_serial_sequence('public.couriers','id'), (select max(id) from public.couriers));
select setval(pg_get_serial_sequence('public.operators','id'), (select max(id) from public.operators));
commit;